services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_TILESERVER_URL=http://localhost:8088
    depends_on:
      - tileserver

  tileserver:
    build:
      context: ./maps
      dockerfile: dockerfile
    container_name: tileserver-gl
    ports:
      - "8088:8080"
    volumes:
      - ./maps/data:/data
      - ./maps/styles:/data/styles
      - ./maps/fonts:/data/fonts
      - ./maps/config.json:/data/config.json
    command: --verbose --config /data/config.json
    restart: unless-stopped
