services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app_signalement
    environment:
      - DB_MIGRATE_FRESH=true  # true = migrate:fresh, false = migrate
      - DB_SEED=true            # true = exécute les seeders, false = ignore
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres
    networks:
      - lalantsikaWeb

  web:
    image: nginx:1.25
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lalantsikaWeb

  postgres:
    image: postgis/postgis:15-3.3
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel 
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lalantsikaWeb

  # Frontend React buildé et servi par Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000/api
    container_name: lalantsika_frontend
    ports:
      - "5173:80"
    depends_on:
      - web
    networks:
      - lalantsikaWeb
    restart: unless-stopped

  # Serveur de cartes TileServer
  tileserver:
    build:
      context: ./maps
      dockerfile: dockerfile
    container_name: lalantsikaWeb_tileserver
    ports:
      - "8088:8080"
    volumes:
      - ./maps/data:/data
      - ./maps/styles:/data/styles
      - ./maps/fonts:/data/fonts
      - ./maps/config.json:/data/config.json
    command: --verbose --config /data/config.json
    networks:
      - lalantsikaWeb
    restart: unless-stopped

networks:
  lalantsikaWeb:
    driver: bridge
  
volumes:
  postgres_data:
