version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_TILESERVER_URL=http://localhost:8080
    stdin_open: true
    tty: true
    depends_on:
      - tileserver

  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - ./maps/data:/data
      - ./maps/styles:/data/styles
      - ./maps/fonts:/data/fonts
      - ./maps/config.json:/data/config.json
    command: --verbose --config /data/config.json
    restart: unless-stopped
